[project]
name = 'sigstrike'
version = '0.1.1'
description = 'Cobalt Strike beacon crawler and parser.'
readme = 'README.md'
requires-python = '>=3.8'
license = 'MIT'
authors = [
    { name = 'Artem Golubin', email = 'me@rushter.com' }
]

[project.scripts]
sigstrike = 'sigstrike._sigstrike:run_cli'

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=62.4", "wheel", "setuptools-rust>=1.5.2"]



[tool.cibuildwheel]
build-frontend = "build"
build-verbosity = 1

macos.before-all = "rustup target add aarch64-apple-darwin x86_64-apple-darwin"
macos.environment = { MACOSX_DEPLOYMENT_TARGET = "10.12" }

skip = [
    "*-manylinux_i686",
    "*-musllinux_i686",
    "*-win32",
    "*-musllinux_aarch64",
    "pp*"
]
macos.archs = ["x86_64", "arm64"]
test-skip = "*-macosx_arm64"

[tool.cibuildwheel.linux]
before-all = "yum install -y openssl openssl-devel pkgconfig libatomic && curl -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal"
environment = { PATH = "$PATH:$HOME/.cargo/bin" }

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-all = "apk --update  add openssl openssl-dev pkgconfig libatomic && curl -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal"