[package]
name = "sigstrike-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.sigstrike]
path = ".."

[[bin]]
name = "beacon"
path = "fuzz_targets/beacon.rs"
test = false
doc = false
bench = false
